import { Inter } from "next/font/google";
import "./globals.css";
import { Suspense } from "react";
import Loading from "./loading";
import CommonLayout from "@/components/common-layout";
import { ClerkProvider } from "@clerk/nextjs";

const inter = Inter({ subsets: ["latin"] });
const defaultFontFamily = "Helvetica, sans-serif";

export const metadata = {
  title: "Job Portal",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <html lang="en">
        <head>
          <style>{`.${inter.className} { font-family: ${
            inter.fontFamily || defaultFontFamily
          }; }`}</style>
        </head>
        <body className={inter.className}>
          <ClerkProvider>
            <Suspense fallback={<Loading />}>
              <CommonLayout />
              {children}
            </Suspense>
          </ClerkProvider>
        </body>
      </html>
    </>
  );
}
